name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  verify_infra:
    name: Validate ARM Template
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Show Azure account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
    
      - name: Validate ARM template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group validate --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ./deploy/azuredeploy.json --parameters ./deploy/azuredeploy.parameters.ci.json